# Generated by Django 5.1.1 on 2025-02-03 22:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toxtempass", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="organization",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="email",
            field=models.EmailField(
                max_length=254,
                unique=True,
                validators=[django.core.validators.EmailValidator()],
                verbose_name="email address",
            ),
        ),
    ]
