# Generated by Django 5.1.1 on 2025-02-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toxtempass", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="person",
            managers=[],
        ),
        migrations.AlterField(
            model_name="person",
            name="orcid_id",
            field=models.CharField(
                blank=True,
                help_text="When the user authenticates with ORCID, this field will be populated with the ORCID iD.",
                max_length=19,
                null=True,
            ),
        ),
    ]
