# Generated by Django 5.1.1 on 2024-10-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toxtempass", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="accepted",
            field=models.BooleanField(
                blank=True, help_text="Marked as final answer.", null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalanswer",
            name="accepted",
            field=models.BooleanField(
                blank=True, help_text="Marked as final answer.", null=True
            ),
        ),
    ]
