# Generated by Django 5.1.6 on 2025-05-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toxtempass', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='usefulness_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
