# Generated by Django 5.1.1 on 2025-02-04 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toxtempass", "0002_person_organization_alter_person_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="investigation",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="investigations",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
