# Generated by Django 5.1.1 on 2024-10-15 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toxtempass", "0002_answer_accepted_historicalanswer_accepted"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="answer_documents",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="historicalanswer",
            name="answer_documents",
            field=models.JSONField(null=True),
        ),
    ]
