# Generated by Django 5.1.1 on 2024-10-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toxtempass", "0003_answer_answer_documents_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="answer_documents",
            field=models.JSONField(
                blank=True,
                help_text="Store list of Filenames used to answer this question.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalanswer",
            name="answer_documents",
            field=models.JSONField(
                blank=True,
                help_text="Store list of Filenames used to answer this question.",
                null=True,
            ),
        ),
    ]
