# Generated by Django 5.1.1 on 2025-02-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toxtempass", "0003_investigation_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assay",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
