# Generated by Django 5.1.6 on 2025-03-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toxtempass', '0004_alter_assay_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='has_accepted_tos',
            field=models.BooleanField(default=False, help_text="Do you accept the terms of service? <a href='https://www.gnu.org/licenses/agpl-3.0.html'>AGPL</a>"),
        ),
    ]
