# Generated by Django 5.1.6 on 2025-07-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toxtempass', '0007_make_questionset_and_section_non_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='additional_llm_instruction',
            field=models.TextField(blank=True, default='', help_text='Extra prompt instructions for the LLM when answering this question.'),
        ),
        migrations.AddField(
            model_name='question',
            name='answering_round',
            field=models.PositiveSmallIntegerField(default=1, help_text='Which round (1, 2, 3, ...) this question should be answered in.'),
        ),
        migrations.AddField(
            model_name='question',
            name='only_subsections_for_context',
            field=models.BooleanField(default=False, help_text='If true, only answers from the subsections listed in subsections_for_context will be used to answer this question.'),
        ),
        migrations.AddField(
            model_name='question',
            name='subsections_for_context',
            field=models.ManyToManyField(blank=True, help_text='List of subsections that provide context for this question.', related_name='context_questions', to='toxtempass.subsection'),
        ),
        migrations.AlterField(
            model_name='assay',
            name='status',
            field=models.CharField(choices=[('none', 'None'), ('scheduled', 'Scheduled'), ('busy', 'Busy'), ('done', 'Done'), ('error', 'Error')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='has_accepted_tos',
            field=models.BooleanField(default=False, help_text="<button type='button' class='btn btn-sm btn-outline-secondary' data-bs-toggle='modal' data-bs-target='#termsModal'>Terms of service</button>", verbose_name='I have read, understood and accept the terms of service.'),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='display_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='label',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
