# Generated by Django 5.1.6 on 2025-07-26 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toxtempass', '0008_question_additional_llm_instruction_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionset',
            options={'verbose_name': 'ToxTemp Question Set Version', 'verbose_name_plural': 'ToxTemp Question Set Versions'},
        ),
    ]
