# Generated by Django 5.1.6 on 2025-07-26 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toxtempass', '0009_alter_questionset_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='assay',
            name='question_set',
            field=models.ForeignKey(default=1, help_text='Which version of the questionnaire this assay is using', on_delete=django.db.models.deletion.PROTECT, related_name='assays', to='toxtempass.questionset'),
            preserve_default=False,
        ),
    ]
