# Generated by Django 5.1.6 on 2025-07-26 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toxtempass', '0010_assay_question_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assay',
            name='question_set',
            field=models.ForeignKey(blank=True, help_text='Which version of the questionnaire this assay is using', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assays', to='toxtempass.questionset'),
        ),
    ]
