# Generated by Django 5.1.6 on 2025-07-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toxtempass', '0011_alter_assay_question_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='only_additional_llm_instruction',
            field=models.BooleanField(default=False, help_text='Extra flag to determine if additional llm instruction shall replace all others.'),
        ),
    ]
