# Generated by Django 5.2.4 on 2025-08-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toxtempass', '0012_alter_questionset_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Control whether this QuestionSet version is shown to users.'),
        ),
    ]
