# Generated by Django 5.1.6 on 2025-09-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toxtempass', '0013_questionset_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='assay',
            name='status_context',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='only_additional_llm_instruction',
            field=models.BooleanField(default=False, help_text='Extra flag to determine if additional llm instruction shall replace all others.'),
        ),
        migrations.AddField(
            model_name='questionset',
            name='hide_from_display',
            field=models.BooleanField(default=True, help_text='If true, this question set will not be displayed in the UI.'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='historicalanswer',
            name='answer_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='organization',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='display_name',
            field=models.CharField(default='v2019', help_text="A user-friendly name for this question set version, e.g., 'ToxTemp Questions v1.0'.", max_length=50),
        ),
    ]
