# Generated by Django 5.2.6 on 2025-09-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toxtempass', '0014_assay_status_context_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='preferences',
            field=models.JSONField(blank=True, help_text='Miscelanous stuff about the user can be stored here', null=True),
        ),
    ]
