# Generated by Django 5.2.6 on 2025-09-16 19:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toxtempass', '0015_person_preferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssayView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_viewed', models.DateTimeField(default=django.utils.timezone.now)),
                ('assay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='toxtempass.assay')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assay_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'assay')},
            },
        ),
    ]
