# Generated by Django 5.2.7 on 2026-01-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toxtempass', '0017_assay_demo_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='assay',
            name='share_files_for_development',
            field=models.BooleanField(default=True, help_text='User consent to share uploaded context files with development team to improve ToxTempAssistant'),
        ),
    ]
