# Generated by Django 5.2.7 on 2025-12-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toxtempass', '0017_assay_demo_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='evidence_text',
            field=models.TextField(blank=True, default='', help_text='Extracted evidence/quotes from source documents used to generate this answer'),
        ),
        migrations.AddField(
            model_name='historicalanswer',
            name='evidence_text',
            field=models.TextField(blank=True, default='', help_text='Extracted evidence/quotes from source documents used to generate this answer'),
        ),
    ]
