# Generated by Django 5.2.9 on 2026-01-10 22:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toxtempass', '0017_assay_demo_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bucket', models.CharField(blank=True, max_length=255)),
                ('object_key', models.CharField(max_length=1024, unique=True)),
                ('original_filename', models.CharField(max_length=512)),
                ('content_type', models.CharField(blank=True, max_length=255)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('available', 'Available'), ('deleted', 'Deleted')], default='available', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toxtempass.answer')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toxtempass.fileasset')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='files',
            field=models.ManyToManyField(blank=True, help_text='Actual stored files (only present if user consented to storage).', null=True, related_name='answers', through='toxtempass.AnswerFile', to='toxtempass.fileasset'),
        ),
        migrations.AddConstraint(
            model_name='answerfile',
            constraint=models.UniqueConstraint(fields=('answer', 'file'), name='uq_answer_file'),
        ),
    ]
