# Generated by Django 5.2.7 on 2025-12-17 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toxtempass', '0018_answer_evidence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='evidence_text',
            new_name='context_used',
        ),
        migrations.RenameField(
            model_name='historicalanswer',
            old_name='evidence_text',
            new_name='context_used',
        ),
    ]
