# Generated by Django 6.0.2 on 2026-03-02 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toxtempass', '0020_workspace_workspaceinvestigation_workspacemember'),
    ]

    operations = [
        migrations.AddField(
            model_name='assay',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user who created this Assay (may differ from the Investigation owner).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assays', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='study',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user who created this Study (may differ from the Investigation owner).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_studies', to=settings.AUTH_USER_MODEL),
        ),
    ]
