# Generated by Django 5.2.11 on 2026-04-12 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toxtempass', '0022_remove_orphaned_files_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_endpoint_index', models.PositiveSmallIntegerField(default=1, help_text='Index of the default Azure endpoint (matches AZURE_E{n}_… env vars).')),
                ('default_model_tag', models.CharField(blank=True, default='', help_text='Tag of the default model on the default endpoint (e.g. GPT4O).', max_length=64)),
                ('allowed_models', models.JSONField(blank=True, default=list, help_text='List of "endpoint_index:tag" strings users may choose from. Empty list = all discovered models are allowed.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LLM Configuration',
                'verbose_name_plural': 'LLM Configuration',
            },
        ),
    ]
