# Generated by Django 5.2.11 on 2026-04-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toxtempass', '0023_llmconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llmconfig',
            name='default_endpoint_index',
        ),
        migrations.RemoveField(
            model_name='llmconfig',
            name='default_model_tag',
        ),
        migrations.AddField(
            model_name='llmconfig',
            name='default_model',
            field=models.CharField(blank=True, default='', help_text='Default deployment as "endpoint_index:tag" (e.g. "1:GPT4O"). Endpoint is derived from the selection. Empty = use first discovered model.', max_length=128),
        ),
    ]
