# Generated by Django 6.0.3 on 2026-04-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toxtempass', '0024_remove_llmconfig_default_endpoint_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmconfig',
            name='last_health_check',
            field=models.JSONField(blank=True, default=dict, help_text='Per-deployment smoke-test results keyed by "index:tag". Populated by the \'Run health check now\' admin action.'),
        ),
    ]
