# Generated by Django 6.0.3 on 2026-04-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toxtempass', '0025_add_llmconfig_health_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='files',
            field=models.ManyToManyField(blank=True, help_text='Actual stored files (only present if user consented to storage).', related_name='answers', through='toxtempass.AnswerFile', to='toxtempass.fileasset'),
        ),
    ]
