# Generated by Django 6.0.4 on 2026-05-08 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toxtempass', '0029_assaycost_cost_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='time_spent_seconds',
            field=models.IntegerField(blank=True, help_text='Automatically measured active time spent on the assay page, in seconds.', null=True),
        ),
        migrations.AlterField(
            model_name='assaycost',
            name='cost_input',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Calculated input cost in EUR for this run.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='assaycost',
            name='cost_input_per_1m',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Snapshot of input price (EUR / 1 M tokens) at run time.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='assaycost',
            name='cost_output',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Calculated output cost in EUR for this run.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='assaycost',
            name='cost_output_per_1m',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Snapshot of output price (EUR / 1 M tokens) at run time.', max_digits=12, null=True),
        ),
    ]
