# Generated by Django 6.0.5 on 2026-06-28 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toxtempass', '0033_feedback_time_spent_seconds_positive'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoAssay',
            fields=[
            ],
            options={
                'verbose_name': 'Demo assay',
                'verbose_name_plural': 'Demo assays',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('toxtempass.assay',),
        ),
    ]
