# Generated by Django 6.0.5 on 2026-06-21 17:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toxtempass', '0033_feedback_time_spent_seconds_positive'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='suggestion_certainty',
            field=models.FloatField(blank=True, help_text='Model self-reported confidence 0–1 for the suggestion (uncalibrated).', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='answer',
            name='suggestion_citations',
            field=models.JSONField(blank=True, help_text='Cited references: list of {"kind", "label", "url"} (url optional).', null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='suggestion_sources',
            field=models.JSONField(blank=True, default=list, help_text='Multi-choice provenance tiers (SuggestionSource values) this suggestion drew on; empty = no suggestion.'),
        ),
        migrations.AddField(
            model_name='answer',
            name='suggestion_text',
            field=models.TextField(blank=True, default='', help_text='Out-of-context suggestion from the optional second LLM round.'),
        ),
        migrations.AddField(
            model_name='historicalanswer',
            name='suggestion_certainty',
            field=models.FloatField(blank=True, help_text='Model self-reported confidence 0–1 for the suggestion (uncalibrated).', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='historicalanswer',
            name='suggestion_citations',
            field=models.JSONField(blank=True, help_text='Cited references: list of {"kind", "label", "url"} (url optional).', null=True),
        ),
        migrations.AddField(
            model_name='historicalanswer',
            name='suggestion_sources',
            field=models.JSONField(blank=True, default=list, help_text='Multi-choice provenance tiers (SuggestionSource values) this suggestion drew on; empty = no suggestion.'),
        ),
        migrations.AddField(
            model_name='historicalanswer',
            name='suggestion_text',
            field=models.TextField(blank=True, default='', help_text='Out-of-context suggestion from the optional second LLM round.'),
        ),
    ]
