# Generated by Django 6.0.5 on 2026-09-12 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toxtempass', '0035_question_riskhunt3r_db_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='ror_checked_organization',
            field=models.CharField(blank=True, default='', help_text='The organization value the ROR lookup last ran for; lets the lookup skip unchanged names.', max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='ror_id',
            field=models.CharField(blank=True, default='', help_text='ROR identifier matched to organization (e.g. https://ror.org/01cesdt21); empty if unmatched.', max_length=64),
        ),
        migrations.AddField(
            model_name='person',
            name='ror_name',
            field=models.CharField(blank=True, default='', help_text='ROR display name of the matched institution; empty if unmatched.', max_length=255),
        ),
    ]
