# Generated by Django 6.0.5 on 2026-06-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toxtempass', '0035_answer_suggestion_certainty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmconfig',
            name='suggestion_model',
            field=models.CharField(blank=True, default='', help_text='Round-2 suggestion deployment as "endpoint_index:tag" (e.g. "6:KIMI"). Blank = reuse the round-1 model for suggestions.', max_length=128),
        ),
    ]
