# Generated by Django 6.0.5 on 2026-06-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toxtempass', '0036_llmconfig_suggestion_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='label',
            field=models.CharField(blank=True, choices=[('metadata', 'Metadata'), ('experimental', 'Experimental'), ('descriptive', 'Descriptive'), ('controls', 'Controls'), ('regulatory', 'Regulatory'), ('interpretive', 'Interpretive')], default='', help_text='Semantic label routing the round-2 suggestion strategy (see Config.SUGGESTION_STRATEGY_BY_LABEL). Blank = default strategy.', max_length=20),
        ),
    ]
