# Generated by Django 6.1.1 on 2026-09-13 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def mark_existing_memberships_notified(apps, schema_editor):
    """Memberships from before notifications existed must not trigger an email."""
    WorkspaceMember = apps.get_model("toxtempass", "WorkspaceMember")
    WorkspaceMember.objects.update(notified_at=models.F("joined_at"))


class Migration(migrations.Migration):

    dependencies = [
        ('toxtempass', '0036_person_ror'),
    ]

    operations = [
        # Existing accounts get False (never deleted for being unconfirmed); the
        # AlterField below makes True the default for accounts created from now on.
        migrations.AddField(
            model_name='person',
            name='delete_if_unconfirmed',
            field=models.BooleanField(default=False, help_text='Delete the account when its email address is still unconfirmed a week after signup. Off for accounts that existed before email confirmation.'),
        ),
        migrations.AlterField(
            model_name='person',
            name='delete_if_unconfirmed',
            field=models.BooleanField(default=True, help_text='Delete the account when its email address is still unconfirmed a week after signup. Off for accounts that existed before email confirmation.'),
        ),
        migrations.AddField(
            model_name='person',
            name='email_confirmed_at',
            field=models.DateTimeField(blank=True, help_text='When the user clicked the link in the confirmation email.', null=True),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='added_by',
            field=models.ForeignKey(blank=True, help_text="Who added this member; empty for the owner's own membership.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='notified_at',
            field=models.DateTimeField(blank=True, help_text='When the member was emailed about being added. Set straight away for the owner and for memberships from before notifications existed.', null=True),
        ),
        migrations.RunPython(
            mark_existing_memberships_notified, migrations.RunPython.noop
        ),
        migrations.CreateModel(
            name='LLMRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('done', 'Done'), ('error', 'Error')], max_length=10)),
                ('model_key', models.CharField(blank=True, default='', help_text='Deployment key, e.g. "1:GPT4O".', max_length=64)),
                ('model_id', models.CharField(blank=True, default='', max_length=128)),
                ('input_tokens', models.PositiveBigIntegerField(default=0)),
                ('output_tokens', models.PositiveBigIntegerField(default=0)),
                ('cost', models.DecimalField(blank=True, decimal_places=6, help_text='Input plus output cost; empty when the model has no pricing tags.', max_digits=12, null=True)),
                ('cost_unit', models.CharField(blank=True, default='', help_text='Currency unit from the cost-unit tag at run time, e.g. "Eur".', max_length=16)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('assay', models.ForeignKey(blank=True, help_text='Empty once the assay is deleted; the spend record stays.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_runs', to='toxtempass.assay')),
                ('user', models.ForeignKey(blank=True, help_text='Who started the run, when known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LLM run',
                'verbose_name_plural': 'LLM runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(db_index=True, max_length=64)),
                ('recipient', models.CharField(blank=True, default='', help_text='Address(es) the email went to, comma-separated for maintainer emails.', max_length=1000)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('merged', 'Sent together with another email'), ('skipped', 'Skipped'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Ids and plain values the email is built from; never tokens.')),
                ('dedup_key', models.CharField(blank=True, default='', help_text='Emails sharing a non-empty key are only sent once.', max_length=255)),
                ('send_after', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('error', models.TextField(blank=True, default='', help_text='Why the email failed or was skipped.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, help_text="The recipient's account; empty for maintainer emails.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('dedup_key', ''), _negated=True), fields=('dedup_key',), name='emaillog_unique_dedup_key')],
            },
        ),
    ]
