# Generated by Django 6.1.1 on 2026-09-14 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toxtempass', '0037_email_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileasset',
            name='delete_after',
            field=models.DateTimeField(blank=True, help_text='When a withdrawn file is deleted; until then the uploader can undo.', null=True),
        ),
        migrations.AddField(
            model_name='fileasset',
            name='withdrawn_at',
            field=models.DateTimeField(blank=True, help_text='When the uploader stopped sharing the file; unused from then on.', null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='pending_email',
            field=models.EmailField(blank=True, default='', help_text='New address waiting for confirmation. The account keeps its current address until the link sent to this one is followed.', max_length=254),
        ),
        migrations.AlterField(
            model_name='fileasset',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('withdrawn', 'No longer shared'), ('deleted', 'Deleted')], default='available', max_length=16),
        ),
        migrations.CreateModel(
            name='FileWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_count', models.PositiveIntegerField()),
                ('withdrawn_at', models.DateTimeField(help_text='When the uploader stopped sharing.')),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('assay', models.ForeignKey(blank=True, help_text='Empty for files never linked to an assay, or once it is deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='toxtempass.assay')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'File withdrawal',
                'verbose_name_plural': 'File withdrawals',
                'ordering': ['-deleted_at'],
            },
        ),
    ]
