# Generated by Django 6.0.5 on 2026-06-29 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toxtempass', '0035_question_riskhunt3r_db_label'),
        ('toxtempass', '0037_question_label'),
    ]

    operations = [
    ]
