# Generated by Django 6.1.1 on 2026-09-14 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toxtempass', '0038_account_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmconfig',
            name='allowed_models',
            field=models.JSONField(blank=True, default=list, help_text='List of "endpoint_index:tag" strings users may choose from. Empty list = users cannot choose and always get the default model (superusers can pick any model).'),
        ),
    ]
