# Generated by Django 6.0.5 on 2026-09-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toxtempass', '0039_llmconfig_allowed_models_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='assaycost',
            name='temperature',
            field=models.CharField(blank=True, default='', help_text='Temperature sent to the model at run time, e.g. "0" or "provider default"; empty for runs recorded before this was tracked.', max_length=32),
        ),
    ]
