# Generated by Django 6.0.5 on 2026-09-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toxtempass', '0040_assaycost_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='llm_abstained',
            field=models.BooleanField(blank=True, help_text="What the LLM decided when it last drafted this answer: True if it said the information was absent from the documents. Recorded at drafting time because the wording is model-specific and a scientist's edit replaces it. Empty for answers no run has drafted, or drafted before this was tracked.", null=True),
        ),
        migrations.AddField(
            model_name='historicalanswer',
            name='llm_abstained',
            field=models.BooleanField(blank=True, help_text="What the LLM decided when it last drafted this answer: True if it said the information was absent from the documents. Recorded at drafting time because the wording is model-specific and a scientist's edit replaces it. Empty for answers no run has drafted, or drafted before this was tracked.", null=True),
        ),
    ]
