# Generated by Django 6.1.1 on 2026-09-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toxtempass', '0041_answer_llm_abstained'),
    ]

    operations = [
        migrations.CreateModel(
            name='AzureFxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=10, help_text='EUR per USD, in force for the month starting effective_start.', max_digits=14)),
                ('observed_on', models.DateField(help_text='Day this rate was first seen in the price list. Azure fixes the rate for a calendar month, so in practice this lands early in the month the rate took effect.', unique=True)),
                ('confirmed_at', models.DateTimeField(auto_now=True, help_text='Last time the price list was checked and still showed this rate. Throttles the check to once a day -- a monthly rate needs no more.')),
                ('source_meter', models.CharField(blank=True, default='', help_text='Meter the ratio was derived from, for auditing.', max_length=200)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Azure FX rate',
                'verbose_name_plural': 'Azure FX rates',
                'ordering': ['-observed_on'],
            },
        ),
        migrations.CreateModel(
            name='LLMCatalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('models_json', models.JSONField(blank=True, default=dict, help_text='Catalogue keyed by model name, each entry holding max_input_tokens, max_output_tokens and per-token prices. Merged on refresh, so a field upstream drops keeps its last known value instead of reverting to unknown.')),
                ('etag', models.CharField(blank=True, default='', help_text='Upstream ETag, sent as If-None-Match on the next refresh.', max_length=200)),
                ('source_url', models.URLField(blank=True, default='', help_text='Which mirror the current copy came from.', max_length=500)),
                ('fetched_at', models.DateTimeField(blank=True, help_text='When the catalogue last actually changed.', null=True)),
                ('checked_at', models.DateTimeField(blank=True, help_text='When upstream was last contacted, changed or not.', null=True)),
            ],
            options={
                'verbose_name': 'LLM Catalogue',
                'verbose_name_plural': 'LLM Catalogue',
            },
        ),
        migrations.AddField(
            model_name='assaycost',
            name='fx_rate',
            field=models.DecimalField(blank=True, decimal_places=10, help_text="USD->EUR rate used to convert the catalogue's USD price at run time. Recorded so the cost stays reproducible after the monthly rate moves; empty when the price was already in the stored unit.", max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='llmrun',
            name='fx_rate',
            field=models.DecimalField(blank=True, decimal_places=10, help_text="USD->EUR rate used to convert the catalogue's USD price at run time. Recorded so the cost stays reproducible after the monthly rate moves; empty when the price was already in the stored unit.", max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='assaycost',
            name='cost_unit',
            field=models.CharField(blank=True, default='', help_text='Currency the cost is expressed in at run time, e.g. "Eur".', max_length=16),
        ),
        migrations.AlterField(
            model_name='llmrun',
            name='cost_unit',
            field=models.CharField(blank=True, default='', help_text='Currency the cost is expressed in at run time, e.g. "Eur".', max_length=16),
        ),
    ]
