# Generated by Django 6.1.1 on 2026-09-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toxtempass', '0042_azurefxrate_llmcatalogue_assaycost_fx_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assaycost',
            name='cache_read_tokens',
            field=models.PositiveBigIntegerField(default=0, help_text="Part of the input tokens served from the provider's prompt cache."),
        ),
        migrations.AddField(
            model_name='assaycost',
            name='cache_write_tokens',
            field=models.PositiveBigIntegerField(default=0, help_text='Part of the input tokens written to the prompt cache (Anthropic).'),
        ),
        migrations.AddField(
            model_name='assaycost',
            name='cost_cache_read_per_1m',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Snapshot of the cached-input price (EUR / 1 M tokens) at run time; empty when the catalogue has none and the input price applied.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='assaycost',
            name='cost_cache_write_per_1m',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Snapshot of the cache-write price (EUR / 1 M tokens) at run time; empty when the catalogue has none and the input price applied.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='llmrun',
            name='cache_read_tokens',
            field=models.PositiveBigIntegerField(default=0, help_text='Part of the input tokens served from the prompt cache.'),
        ),
        migrations.AddField(
            model_name='llmrun',
            name='cache_write_tokens',
            field=models.PositiveBigIntegerField(default=0, help_text='Part of the input tokens written to the prompt cache.'),
        ),
        migrations.AlterField(
            model_name='assaycost',
            name='cost_input',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Calculated input cost in EUR for this run, cached tokens included.', max_digits=12, null=True),
        ),
    ]
