# Generated by Django 6.1.1 on 2026-10-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toxtempass', '0044_workspace_api_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspaceapitoken',
            name='last_pdf_at',
            field=models.DateTimeField(blank=True, help_text='When this token last requested a PDF; drives the PDF cool-down.', null=True),
        ),
    ]
