# Generated by Django 6.1.1 on 2026-10-08 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toxtempass', '0045_api_token_last_pdf_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacemember',
            name='credit_consent_at',
            field=models.DateTimeField(blank=True, help_text="When the member agreed to be credited by name (name, organization and ORCID iD, never email) as an author in what this workspace's API tokens read. Empty means they appear as 'Contributor (not named)'. Set on accepting an invitation; members from before invitations existed, or added in the admin, confirm it themselves.", null=True),
        ),
        migrations.CreateModel(
            name='WorkspaceInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Member'), ('admin', 'Admin')], default='member', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_invitations', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='toxtempass.workspace')),
            ],
            options={
                'unique_together': {('workspace', 'user')},
            },
        ),
    ]
