# Generated by Django 6.1.1 on 2026-10-08 20:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toxtempass', '0046_workspace_invitations'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiPdfJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='queued', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the file is deleted.', null=True)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('assay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_pdf_jobs', to='toxtempass.assay')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_jobs', to='toxtempass.workspaceapitoken')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_jobs', to='toxtempass.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='toxtempass__status_0d8792_idx')],
            },
        ),
    ]
