# Generated by Django 6.1.1 on 2026-10-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toxtempass', '0047_api_pdf_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='credit_by_name',
            field=models.BooleanField(blank=True, default=None, help_text="Whether the person may be named (name, organization and ORCID iD, never email) as an author in what a workspace API token reads. Applies to every workspace. Empty means they have not decided: they appear as 'Contributor (not named)', and accepting a workspace invitation turns it on. False is an explicit choice, which accepting an invitation never overrides.", null=True),
        ),
        migrations.RemoveField(
            model_name='workspacemember',
            name='credit_consent_at',
        ),
    ]
