# Generated by Django 6.1.1 on 2026-10-08 21:36

from django.db import migrations, models


def carry_over_agreements(apps, schema_editor):
    """Anyone who had agreed to be credited in any workspace keeps that agreement."""
    Person = apps.get_model("toxtempass", "Person")
    WorkspaceMember = apps.get_model("toxtempass", "WorkspaceMember")
    agreed = (
        WorkspaceMember.objects.filter(credit_consent_at__isnull=False)
        .values_list("user_id", flat=True)
        .distinct()
    )
    Person.objects.filter(pk__in=list(agreed)).update(credit_by_name=True)


def restore_agreements(apps, schema_editor):
    """Give every membership of a credited person back its agreement date."""
    from django.utils import timezone

    WorkspaceMember = apps.get_model("toxtempass", "WorkspaceMember")
    WorkspaceMember.objects.filter(user__credit_by_name=True).update(
        credit_consent_at=timezone.now()
    )


class Migration(migrations.Migration):

    dependencies = [
        ('toxtempass', '0047_api_pdf_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='credit_by_name',
            field=models.BooleanField(blank=True, default=None, help_text="Whether the person may be named (name, organization and ORCID iD, never email) as an author in what a workspace API token reads. Applies to every workspace. Empty means they have not decided: they appear as 'Contributor (not named)', and accepting a workspace invitation turns it on. False is an explicit choice, which accepting an invitation never overrides.", null=True),
        ),
        migrations.RunPython(carry_over_agreements, restore_agreements),
        migrations.RemoveField(
            model_name='workspacemember',
            name='credit_consent_at',
        ),
    ]
