# Generated by Django 6.1.1 on 2026-10-08 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toxtempass', '0048_global_credit_by_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='credit_by_name',
            field=models.BooleanField(default=True, help_text="Whether the person may be named (name, organization and ORCID iD, never email) as an author in what a workspace API token reads. On unless the person switches it off, in the Privacy tab, and then it applies to every workspace. Off means they appear as 'Contributor (not named)'."),
        ),
    ]
