name: REBUILD ON SERVER
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GIT_ACTIONS }}" > ~/.ssh/github_action
          chmod 600 ~/.ssh/github_action

      - name: Deploy to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.REMOTE_SERVER_ADDRESS }}
          username: ${{ vars.REMOTE_SERVER_USERNAME }}
          key_path: /home/runner/.ssh/github_action
          script: |
            cd "${{ vars.REMOTE_SERVER_PATH }}"
            git pull origin main
            docker compose up --build -d
