name: REBUILD ON SERVER
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.GIT_ACTIONS }}" > ~/.ssh/github_action
          chmod 600 ~/.ssh/github_action

      - name: Deploy to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.REMOTE_SERVER_ADDRESS }}
          username: ${{ vars.REMOTE_SERVER_USERNAME }}
          key_path: /home/runner/.ssh/github_action
          script: |
            cd "${{ vars.REMOTE_SERVER_PATH }}"
            git pull origin main
            GIT_HASH=$(git rev-parse HEAD)  # super user has different variables defined so we have to inject them at sudo
            sudo TOXTEMPASS_GIT_HASH=$GIT_HASH docker compose up --build -d  # passwordless sudo enabled via /etc/sudoers.d/90-deploy-docker
