name: Release

permissions:
  contents: write # give GITHUB_TOKEN push/tag rights

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  semantic-release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    # 1) inject the token into every step in this job
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # 2) explicitly pass the token to the checkout action
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Python & Poetry
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies (incl. dev)
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-interaction --no-ansi --extras dev

      - name: Debug GITHUB_TOKEN
        run: |
          echo "Is GITHUB_TOKEN non‑empty? -> '${GITHUB_TOKEN:+yes}'"
          # this should print "yes"

      - name: Publish Release (bump/tag/changelog)
        run: |
          poetry run semantic-release publish
