name: Release

permissions:
  contents: write

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  semantic-release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          # these plugins will generate/update CHANGELOG.md and push the updated files + tag
          extra_plugins: |
            @semantic-release/changelog@6
            @semantic-release/git@6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
